### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [your-sdnss/grid-template-hw#1]
1)
цвет заполнителя и оформление в фокусе не соответствуют макету
![image](https://user-images.githubusercontent.com/8464662/112441498-ee046700-8d53-11eb-807d-4b982b748ea2.png)

2)
оформление не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/112442023-0d9b8f80-8d54-11eb-9dc9-19a6837af986.png)

3)
отступы не соответствуют, проверяйте для всех разрешений
![image](https://user-images.githubusercontent.com/8464662/112442176-3f145b00-8d54-11eb-83af-ea95e47cc41e.png)
![image](https://user-images.githubusercontent.com/8464662/112442211-489dc300-8d54-11eb-86b7-318b3a8c729c.png)

4)
некорректный размер текста
![image](https://user-images.githubusercontent.com/8464662/112442278-57847580-8d54-11eb-9eba-89cae7ed4d64.png)

5)
неправильное отображение формы для всех ращрешений
![image](https://user-images.githubusercontent.com/8464662/112442314-610ddd80-8d54-11eb-9d3c-fcb129828c04.png)

6)
неправильное отображение блока
![image](https://user-images.githubusercontent.com/8464662/112442417-771b9e00-8d54-11eb-99af-52817dbb5f41.png)
![image](https://user-images.githubusercontent.com/8464662/112442449-83076000-8d54-11eb-857f-a87db206365b.png)

7)
некорретный вид
![image](https://user-images.githubusercontent.com/8464662/112442478-8995d780-8d54-11eb-8266-15db4021a412.png)

8)
неправильная толщина разделителя
![image](https://user-images.githubusercontent.com/8464662/112442566-a3cfb580-8d54-11eb-8ef1-43ea59483ce5.png)

**Comment by your-sdnss** [comment]
Постарался исправить данный список проблем

**Comment by Alecto** [comment]
добрый день. 2 ссылочки пожалуйста, пока нечего проверять

пт, 26 мар. 2021 г. в 14:55, your-sdnss ***@***.***>:

**Comment by Alecto** [comment]
3 и 6 - не исправлены, неправильные отступы

**Comment by Alecto** [comment]
6 - не исправлено

**Comment by your-sdnss** [comment]
> 6 - не исправлено

Пожалуйста, если не тяжело, не могли бы вы присалть скрины, что не так отображается?
![Screenshot_58](https://user-images.githubusercontent.com/80222218/114384801-e0464280-9b97-11eb-998e-bd084a8384e8.png)
![Screenshot_60](https://user-images.githubusercontent.com/80222218/114384808-e2a89c80-9b97-11eb-8a9f-ad9f8a23d07c.png)
![Screenshot_61](https://user-images.githubusercontent.com/80222218/114384813-e3d9c980-9b97-11eb-8d3f-3ed45d05a288.png)

**Comment by Alecto** [comment]
Я вам делал скрины, да и здесь видно - отступы заголовка

**Comment by your-sdnss** [comment]
> Я вам делал скрины, да и здесь видно - отступы заголовка

убрал margin-top у заголовка

https://github.com/your-sdnss/grid-template-hw/tree/master
https://your-sdnss.github.io/grid-template-hw/

**Comment by Alecto** [comment]
и это правильно )
отлично, работа принята.

напишите пожалуйста, кому ставить оценку, потому что из переписки гитхаб
эта инфа потерялась.

**Comment by your-sdnss** [comment]
> и это правильно ) отлично, работа принята. напишите пожалуйста, кому ставить оценку, потому что из переписки гитхаб эта инфа потерялась.

Сидоров Максим, сб/вс 12-14
